public/index.html
- index.html 초기 설정 수정
- index.html 초기 설정 코드 수정
=> Modify : index.html 코드 수정

src/common/post/Post.Style.jsx, src/common/post/Post.jsx, src/common/post/postContents/PostContents.Style.jsx, src/common/post/postContents/PostContents.jsx, src/common/post/postUserInfo/PostUserInfo.Style.jsx, src/common/post/postUserInfo/PostUserInfo.jsx
-
- 유저 프로필, 게시글 이미지에 임시로 CDN 이미지를 넣어두었습니다
close : #5
=> 💄 Feat : Post 컴포넌트 UI 구현

src/common/tabMenu/TabMenu.Style.jsx, src/common/tabMenu/TabMenu.jsx
- 하단 탭 메뉴의 UI를 구현했습니다.
-
close : #
=> Feat : TabMenu UI 구현

src/common/topBanner/TopBanner.Style.jsx, src/common/topBanner/TopBanner.jsx
-
- 페이지 작성 이후, Link 수정 필요
close : #
=> Feat : 탑 배너  UI구현

src/common/comment/Comment.Style.jsx, src/common/comment/Comment.jsx
- 댓글 입력창의 UI를 구현했습니다.
- useState 사용한 부분은 atom 파일로 분리할 예정입니다.
close : #
=> Feat : Comment UI 구현

src/common/alert/Alert.Style.jsx, src/common/alert/Alert.jsx
- Alert box UI 구현했습니다.
-
close : #
=> Feat : Alert UI 구현

src/common/product /Product.Style.jsx, src/common/product /Product.jsx, src/common/textActiveInput/TextActiveInput.Style.jsx, src/common/textActiveInput/TextActiveInput.jsx, src/common/userBanner/UserBanner.Style.jsx, src/common/userBanner/UserBanner.jsx
- common 요소 UserBanner UI 추가
-
close : #4
=> Feat : UserBanner UI 구현

src/common/topBanner/TopBanner.Style.jsx
=> 🩹Modify : 스프라이트이미지 참조경로 수정

src/pages/profileEdit/ProfileEdit.Style.jsx, src/pages/profileEdit/ProfileEdit.jsx
- 프로필 수정 페이지의 UI를 구현했습니다.
-
close : #
=> Feat : ProfileEdit 페이지 UI 구현

src/pages/postUpload/PostUpload.Style.jsx, src/pages/postUpload/PostUpload.jsx
-
- Eslint 설정으로 인해 셀프 클로징 태그가 아닌 경우 요소 내부를 비워둘 수 없는 이슈가 있어 임시로 textarea 태그를 셀프 클로징 처리했습니다
close : #23
=> Feat : PostUpload 페이지 UI 구현

src/pages/addProduct/AddProduct.Style.jsx, src/pages/addProduct/AddProduct.jsx
- 상품 등록 페이지의 UI를 구현했습니다.
-
close : #
=> Feat : AddProduct 페이지 UI 구현

src/pages/productEdit/ProductEdit.Style.jsx, src/pages/productEdit/ProductEdit.jsx
- 상품 수정 페이지의 UI를 구현했습니다.
-
close : #
=> Feat : ProductEdit 페이지 UI 구현

src/pages/postDetail/PostDetail.Style.jsx, src/pages/postDetail/PostDetail.jsx
- 페이지 세로 스크롤 관련 코드를 수정했습니다
- 접근성을 위해 페이지의 타이틀을 추가했습니다
-
close : #33
=> Modify : PostDetail 페이지 스크롤 관련 코드 수정

src/common/tabMenu/TabMenu.Style.jsx, src/common/tabMenu/TabMenu.jsx, src/styles/Globalstyled.jsx
-
- 하단 탭메뉴의 보더탑을 정했습니다.
- sub2 글자색을 추가했습니다.
- 탭메뉴가 사용 가능하게 주석을 변경했습니다.
close : #
=> Modify : TabMenu 코드 수정

src/common/topBanner/TopBanner.Style.jsx, src/common/topBanner/TopBanner.jsx
=> :lipstick:Modify : 탑 배너 보더추가 및 폰트 수정

src/pages/home/Home.Style.jsx, src/pages/home/Home.jsx
=> Feat : Home 페이지 UI 구현

src/pages/postDetail/PostDetail.Style.jsx
- TopBanner 컴포넌트 border 추가로 원래 있던 border와 겹치는 현상을 수정했습니다
- #dbdbdb컬러는 모두 변수로 바꿨습니다
-
close : #
=> Modify : 상단 탭 border 겹치는 현상 수정

src/common/inputBox/InputBox.jsx
- 인풋박스에 id를 props로 추가했습니다.
-
close : #
=> Modify : InputBox 수정

src/common/button/Button.Style.jsx, src/common/button/Button.jsx
=> Feat : Button 컴포넌트 추가

src/common/inputBox/inputBox.Style.jsx, src/pages/followerList/FollowerList.Style.jsx, src/pages/followerList/FollowerList.jsx, src/pages/followingList/FollowingList.Style.jsx, src/pages/followingList/FollowingList.jsx, src/pages/profileEdit/ProfileEdit.Style.jsx, src/pages/profileEdit/ProfileEdit.jsx
- Follower & Following 리스트 페이지의 UI를 구현했습니다.
- ProfileEdit 페이지에 InputBox 컴포넌트로 변경했습니다.
- InputBoxStyle 폴더명의 오타를 수정했습니다. -> 는 반영이 안되네... 왜지
-
close : #
=> Feat : Follower & Following 리스트 페이지 UI 구현

src/common/topBanner/TopBanner.Style.jsx, src/common/topBanner/TopBanner.jsx
=> Modify : 탑 배너 UI 수정(버튼컴포넌트사용)

src/pages/chatRoom/ChatRoom.Style.jsx, src/pages/chatRoom/ChatRoom.jsx
=> Feat : ChatRoom 페이지 UI 구현

src/pages/home/Home.Style.jsx, src/pages/home/Home.jsx
- 기존 버튼 요소를 공통컴포넌트로 교체했습니다
-
close : #
=> Modify : 버튼 요소 컴포넌트로 교체

src/App.jsx, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx
- email login page UI 구현
-
close : #59
=> Feat : emaillogin page UI 구현

src/common/userBanner/UserBanner.Style.jsx, src/common/userBanner/UserBanner.jsx
- userBanner을 common의 button을 활용해서 수정했습니다. 
- user image는 임의로 넣었습니다.
close : #62
=> Modify : UserBanner button 적용 수정

src/App.jsx, src/pages/search/Search.Style.jsx, src/pages/search/Search.jsx
- Search 페이지에서 보여주는 검색 리스트의 Li요소를 UserBanner 컴포넌트로 교체했습니다
-
close : #
=> Modify : UserBanner 컴포넌트로 교체

src/App.jsx, src/pages/join/Join.Style.jsx, src/pages/join/Join.jsx
=> Feat : Join Page UI 구현

src/App.jsx, src/pages/snsLogin/SnsLogin.Style.jsx
=> Feat : 페이지 라우팅 설정

src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx
=> Modify : UI 수정 (heigh 조절 및 하단 탭메뉴 고정)

src/pages/chatRoom/ChatRoom.Style.jsx, src/pages/home/Home.Style.jsx, src/pages/home/Home.jsx, src/pages/postDetail/PostDetail.Style.jsx, src/pages/postDetail/PostDetail.jsx, src/pages/postUpload/PostUpload.Style.jsx, src/pages/postUpload/PostUpload.jsx, src/pages/search/Search.Style.jsx
- 기존 뷰포트 기준 Height값에서 820px 고정값으로 수정했습니다
-
close : #
=> Modify : 페이지별 Height속성 고정단위로 변경

src/common/userBanner/UserBanner.jsx
- UserBanner Button을 state에 따라 사용할 수 있게 변경했습니다.
-
close : #
=> Modify : UserBanner Button 수정

src/pages/page404/Page404.Style.jsx
- page404에 임의로 넣었던 이미지를 로고 이미지로 변경했습니다.
-
close : #
=> Modify : page404 이미지 변경

src/pages/snsLogin/SnsLogin.Style.jsx
- snsLogin page 이미지 경로 및 사이즈 변경
-
close : #
=> Modify : snsLogin page image 경로 및 사이즈 수정

src/pages/splash/Splash.Style.jsx
- Splash Page 이미지 테두리 생기는 현상을 수정했습니다.
-
close : #
=> Modify : Splash Page image 테두리 수정

src/pages/snsLogin/SnsLogin.Style.jsx
- snsLogin Page 이미지 테두리 수정했습니다.
-
close : #
=> Modify : SnsLogin Page 이미지 수정

src/common/userBanner/UserBanner.jsx, src/pages/home/Home.jsx
- UserBanner 버튼을 세가지 타입으로 수정했습니다. 버튼이 없는 형태, 팔로우 버튼, 취소 버튼으로 나누어져있습니다!
-
close : #
=> Add : UserBanner 여러 버튼 타입 설정

src/common/userBanner/UserBanner.jsx
=> Delete : UserBanner 주석 삭제

src/common/button/Button.Style.jsx, src/common/button/Button.jsx
=> Modify : Button컴포넌트 props에 onClick, isActive 추가

src/App.jsx, src/common/postModal/PostModal.Style.jsx, src/common/postModal/PostModal.jsx
=> Feat : postModal UI 구현

src/common/post/Post.Style.jsx, src/pages/chatRoom/ChatRoom.Style.jsx, src/pages/home/Home.Style.jsx, src/pages/home/Home.jsx, src/pages/postDetail/PostDetail.Style.jsx, src/pages/postDetail/PostDetail.jsx, src/pages/postUpload/PostUpload.Style.jsx, src/pages/search/Search.Style.jsx, src/pages/search/Search.jsx
-
- 백그라운드 이미지 좌표값을 수정했습니다
close : #
=> Modify : 스프라이트 시트 좌표 수정

src/pages/home/Home.jsx
-
- Home페이지에서 Search페이지로 가는 링크를 추가했습니다
close : #88
=> Feat : Home페이지에 링크 추가

src/common/topBanner/TopBanner.Style.jsx
=> Modify : 탑배너 이미지스프라이트 수정

src/common/postModal/PostModal.jsx, src/common/product/Product.Style.jsx, src/common/product/Product.jsx, src/common/topBanner/TopBanner.jsx, src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx
=> Modify : 프로필페이지 모달창 수정

src/pages/snsLogin/SnsLogin.Style.jsx, src/pages/snsLogin/SnsLogin.jsx
- sns login page 하단의 이메일로 로그인, 회원가입 페이지로 이동 기능 추가
-
close : #
=> Feat : 이메일로 로그인, 회원가입 페이지로 이동 기능 추가

src/common/postModal/PostModal.jsx, src/common/topBanner/TopBanner.jsx, src/pages/chatList/ChatList.jsx, src/pages/chatRoom/ChatRoom.jsx
=> Modify : 채팅 페이지별 모달창 추가구현

src/common/post/Post.Style.jsx, src/common/post/Post.jsx
- 좋아요 기능, 본문 클릭 시 게시글의 id에 따라 상세페이지로 이동하는 기능을 추가했습니다
- `data`로 포스트 데이터를 전달하시면 됩니다
- 
close : #90
=> Feat : Post 컴포넌트 기능 구현

src/common/comment/Comment.Style.jsx, src/common/comment/Comment.jsx, src/common/inputBox/InputBox.jsx, src/pages/profileEdit/ProfileEdit.jsx
- Comment 컴포넌트에 input에 따른 label을 ir 기법으로 추가했습니다.
- input창에 텍스트를 입력하면 게시 버튼 색이 바뀝니다.
-
close : #
=> Add : Comment 컴포넌트에 게시 버튼 활성화 기능 추가

src/api/uploadImgAPI.js, src/api/uploadPostAPI.js, src/pages/postUpload/PostUpload.jsx
- 사용자 입력 시 업로드 버튼 활성화
- 이미지 파일 선택 시 프리뷰
- 선택한 이미지 파일 삭제 기능
- 게시글 업로드 기능
- 사용자 프로필 이미지는 추후 recoil state를 사용해 받을 예정입니다
close : #101
=> Feat : PostUpload 페이지 기능 구현

src/api/getPostDetailAPI.js, src/pages/postDetail/PostDetail.Style.jsx, src/pages/postDetail/PostDetail.jsx
- 포스트 작성 페이지에서 업로드 완료 시 해당 포스트 디테일 페이지로 넘어갑니다
- 모달 on/off 기능을 추가했습니다
- 
close : #106
=> Feat : PostDetail 페이지 기능 구현

src/api/emailLoginAPI.js, src/atoms/LoginedUser.js, src/common/button/Button.jsx, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx
- email login 기능 추가
- 유효성 검사 및 api 수정 예정입니다. 또한 button에 disabled 속성 추가했습니다.
close : #
=> Feat : emailLogin 기능 구현

src/api/likeAPI.js, src/api/unlikeAPI.js, src/common/post/Post.Style.jsx, src/common/post/Post.jsx
- 좋아요, 좋아요 취소 API 파일을 분리했습니다
- 좋아요 개수 데이터를 받아서 표시하도록 변경했습니다
- 사용자 프로필 페이지에서 게시글 본문을 누를 경우에만 게시글 상세페이지로 이동하도록 수정했습니다
-
close : #108
=> Modify : Post컴포넌트 navigate기능 수정, 좋아요 기능 API 분리

src/api/emailLoginAPI.js, src/pages/emailLogin/EmailLogin.jsx, src/pages/profileSetting/ProfileSetting.jsx
- email password validation 추가했습니다.
- 추가 수정 예정입니다.
close : #
=> Add : validation 기능  추가

src/api/loadPostsAPI.js, src/api/loadProductsAPI.js, src/api/loadProfileAPI.js, src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx
=> Add : 프로필페이지 기능구현

src/api/deleateCommentAPI.js, src/api/getCommentListAPI.js, src/api/leaveCommentAPI.js, src/common/comment/Comment.Style.jsx, src/common/comment/Comment.jsx, src/pages/postDetail/PostDetail.jsx
- 게시글 상세페이지 내 댓글 작성 기능을 추가했습니다
- 더보기 버튼 클릭 시 모달 오픈, 배경화면 클릭 시 모달이 닫히는 기능을 추가했습니다
- 
close : #112
=> Feat : PostDetail 페이지 내 댓글 작성 기능 구현

src/common/comment/Comment.jsx, src/common/post/Post.jsx, src/pages/postDetail/PostDetail.jsx
- 댓글 카운트 기능을 추가했습니다
- PostDetail 페이지에서는 댓글 작성 시 실시간으로 카운트가 변합니다
- Profile 페이지에서는 댓글 카운트 정보를 불러와 보여줍니다
close : #117
=> Add : Post 컴포넌트의 댓글 카운트 기능 추가

src/pages/postDetail/PostDetail.jsx, src/pages/postUpload/PostUpload.jsx
- 게시글 상세 페이지 내 댓글 작성 시간을 보여주는 기능을 추가했습니다
- 게시글 업로드 페이지 코드 내의 오타를 수정했습니다
close : #120
=> Add : 댓글 작성 시간 표시 기능 추가, 오타 수정

src/api/accountnameValidAPI.js, src/api/editProfileAPI.js, src/common/inputBox/InputBox.jsx, src/pages/profileEdit/ProfileEdit.jsx
- 프로필 수정 관련 api를 구현했습니다.
- 프로필 수정 페이지의 기능을 구현했습니다.
- 유저의 id에 대한 유효성 검사와 중복 검사를 진행합니다.
- 로그인 api가 구현된 후, 현재 로그인한 유저의 id로 api를 불러오는 것으로 수정할 예정입니다.
-
close : #
=> Feat : 프로필 수정 페이지 기능 구현

src/api/emailLoginAPI.js, src/api/joinAPI.js, src/pages/emailLogin/EmailLogin.jsx, src/pages/profileSetting/ProfileSetting.jsx
inputbox변경사항 취소
- emailLoginAPI, joinAPI 수정 및 추가
- inputBox.jsx 수정 내용 변경 후 충돌이 생겨 Feat/emailLogin branch에서 git commit --amend git push -f 로 작업 진행했습니다.
close : #
=> Modify : emailLoginAPI, joinAPI수정

src/api/searchUserAPI.js, src/common/topBanner/TopBanner.jsx, src/common/userBanner/UserBanner.jsx, src/pages/search/Search.jsx
- 사용자 검색 기능을 추가했습니다
- userbanner, topbanner 컴포넌트 수정사항이 있습니다
close : #
=> Feat : 사용자 검색 기능 구현

src/common/post/Post.jsx, src/common/postModal/PostModal.Style.jsx, src/common/postModal/PostModal.jsx, src/pages/profile/Profile.jsx
=> Add : 모달창 UI 및 추가 기능구현

src/api/followAPI.js, src/api/loadFollowerListAPI.js, src/api/loadFollowingListAPI.js, src/api/unfollowAPI.js, src/common/post/Post.jsx, src/common/postModal/PostModal.Style.jsx, src/common/postModal/PostModal.jsx, src/common/topBanner/TopBanner.jsx, src/common/userBanner/UserBanner.Style.jsx, src/common/userBanner/UserBanner.jsx, src/pages/followerList/FollowerList.jsx, src/pages/followingList/FollowingList.jsx, src/pages/profile/Profile.jsx
- 팔로우 언팔로우버튼 기능구현 완료
- 팔로워 팔로잉 페이지 구현완료
- 유저배너 팔로워기능 구현완료
- 유저배너 Link 기능 추가 (추후 경로보완 필요)
- 
-
close : #129
=> Feat : 팔로워 팔로잉 페이지 기능구현

src/api/searchUserAPI.js, src/pages/postDetail/PostDetail.jsx, src/pages/search/Search.Style.jsx, src/pages/search/Search.jsx
- 검색어 입력 시 매칭되는 단어는 강조해 보여주는 기능을 추가했습니다
- startsWith메서드를 사용해 입력값이 공백문자로 시작할 경우 API가 호출되지 않도록 처리했습니다
close : #127
=> Add : 검색어 입력 시 매칭된 단어 강조표시 기능 구현

src/api/emailLoginAPI.js, src/api/joinAPI.js, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx
- inputBox 수정된 내용 반영 및 email, password validation 코드 수정
-
close : #
=> Modify : emailLogin inputbox validation 수정

src/api/emailLoginAPI.js, src/pages/emailLogin/EmailLogin.jsx
- emailLoginAPI 기능추가
-
close : #
=> Add : emailLoginAPI 정리 및 기능 추가

src/common/postModal/PostModal.jsx, src/common/product/Product.Style.jsx, src/common/product/Product.jsx, src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx
=> Add : product 모달창 웹사이트에서 상품보기 버튼 구현

src/api/joinAPI.js, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx
- Join page 기능 구현
- 이메일 입력시 가입여부 확인 기능 추가 예정 및 버튼 마진 조절 예정입니다.
close : #
=> Feat : 회원가입 기능 구현

src/api/joinAPI.js, src/pages/join/Join.jsx
- join page 이메일 검증 수정 중입니다.
- join page 계정검증 및 이메일 검증 추가 예정입니다.
close : #138
=> Add : joinPage 이메일 검증 수정

src/api/getFollowersPostsAPI.js, src/pages/home/Home.jsx
=> Feat : 팔로워 게시글 목록 표시 기능 구현

src/common/post/Post.jsx
=> 🩹 Modify : 더보기 버튼 클릭 시 페이지 이동 이벤트가 발생하는 문제 수정

src/api/uploadPostAPI.js, src/pages/postUpload/PostUpload.Style.jsx, src/pages/postUpload/PostUpload.jsx
- 최대 세 장까지 사진을 업로드하는 기능을 추가했습니다
- 세 장 이상의 파일을 첨부하려고 시도할 경우 알림창을 띄우도록 처리했습니다
close : #145
=> Add : 사진 여러장 업로드 기능 추가

package-lock.json, package.json, src/atoms/LoginData.js, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx
- loginData atom 파일 추가
- login data username, accountname, email, password, intro, image atom 추가했습니다! 
close : #
=> Add : LoginData atom 파일 추가 및 emailLogin page 수정

src/pages/profile/Profile.Style.jsx
=> Modify : 사용자프로필이미지 수정, 판매중인 상품 레이아웃수정

src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.Style.jsx, src/pages/join/Join.jsx, src/pages/profileSetting/ProfileSetting.jsx
- join page handleClick 기능추가 및 코드 구조 수정
-
close : #136
=> Modify : Join Page 코드 구조 수정 및 handleClick 기능 수정

src/api/emailDuplicateAPI.js, src/api/joinAPI.js, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx
- join page 이메일 중복 검사 기능 추가
- 중복검사 기능 수정 예정입니다.
close : #
=> Add : join Page 이메일 중복검사 기능 추가

src/atoms/LoginData.js, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx
- email login page atom수정 및 Link스타일링
-
close : #
=> Modify : email Login page atom, Link 수정

src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx
=> Modify : 아톰값 불러오기 및 ListImg 여러장이미지 처리

src/common/postModal/PostModal.jsx
=> Modify : 모달창 navigate 경로 일부 수정

src/pages/emailLogin/EmailLogin.jsx, src/pages/snsLogin/SnsLogin.Style.jsx, src/pages/snsLogin/SnsLogin.jsx
- sns Login page Link스타일 변경
-
close : #
=> Modify : snsLogin page Link 스타일 변경

src/pages/snsLogin/SnsLogin.Style.jsx
- Link font style 수정
-
close : #
=> Modify : Link 글씨 스타일 수정

src/api/uploadMultipleImgAPI.js, src/api/uploadPostAPI.js, src/common/post/Post.jsx, src/pages/postUpload/PostUpload.jsx
=> Modify : PostUpload 페이지의 이미지 프리뷰 함수 수정

src/api/emailDuplicateAPI.js, src/api/joinAPI.js, src/common/inputBox/InputBox.jsx, src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/join/Join.Style.jsx, src/pages/join/Join.jsx
- 유저 이메일 중복 검사 완료했습니다.
-
close : #
=> Modify : join page 유저이메일 중복 검사 수정

src/pages/emailLogin/EmailLogin.jsx
- btnActive === true일 경우 loginAPI실행
-
close : #
=> Modify : btnActive 활성화 되어있을 경우 API실행

src/api/uploadMultipleImgAPI.js, src/api/uploadPostAPI.js, src/common/post/Post.jsx, src/pages/postUpload/PostUpload.jsx
=> Modify : 서버 URL 만다린으로 변경

src/common/post/Post.Style.jsx, src/common/post/Post.jsx, src/pages/home/Home.jsx, src/pages/postUpload/PostUpload.jsx
- 이미지 슬라이더의 인디케이터 색상을 변경했습니다
- 이미지 슬라이더의 스와이프 기능을 추가했습니다
- 로그인 후 홈 화면으로 이동시 피드데이터를 안전하게 받을 수 있도록 옵셔널 체이닝을 사용했습니다
- atom을 사용해 업로드 페이지의 유저 프로필 이미지를 삽입했습니다
-
close : #170
=> Modify : 이미지 슬라이드 스와이프 기능 추가, 인디케이터 색상 변경 외

src/atoms/LoginData.js
- LoginData atom 파일 수정
- default 문자열 형태로 변경했습니다.
close : #
=> Modify : LoginData.js atom파일 수정

src/common/post/Post.Style.jsx, src/pages/chatRoom/ChatRoom.Style.jsx, src/pages/chatRoom/ChatRoom.jsx
- Post 컴포넌트의 인디케이터 색상을 메인컬러로 변경했습니다
- ChatRoom 페이지 진입 시 페이드인 효과를 추가했습니다
- 채팅 상세 마크업은 추후 ChatList 수정 시에 함께 변경합니다
close : #174
=> Modify : Post컴포넌트 인디케이터 색상 변경, ChatRoom 페이지 페이드인 애니메이션 추가

src/api/emailLoginAPI.js, src/pages/emailLogin/EmailLogin.jsx
- 이메일 로그인 시 유저정보가 제대로 전달되지 않는 문제를 수정했습니다
-
close : #
=> 🩹Modify : 이메일 로그인 비동기처리 코드 수정

src/pages/profileSetting/ProfileSetting.jsx
=> Modify : profileSetting page 수정

src/pages/addProduct/AddProduct.jsx, src/pages/home/Home.Style.jsx, src/pages/postDetail/PostDetail.Style.jsx, src/pages/postUpload/PostUpload.Style.jsx, src/pages/profileEdit/ProfileEdit.jsx
- 홈 페이지, 포스트 업로드 & 디테일 페이지에서 y 스크롤바를 숨깁니다.
- 상품 등록 페이지에서 상품 등록 후 프로필 페이지로 이동합니다.
-
close : #
=> Modify : Post 관련 페이지들 스크롤 및 UI 수정

src/common/alert/Alert.Style.jsx, src/common/alert/Alert.jsx, src/common/postModal/PostModal.Style.jsx, src/common/postModal/PostModal.jsx, src/common/topBanner/TopBanner.jsx, src/pages/postDetail/PostDetail.jsx, src/pages/profile/Profile.jsx
=> Modify : 모달창 추가 기능구현

src/pages/postUpload/PostUpload.Style.jsx, src/pages/postUpload/PostUpload.jsx
- 다중 이미지 미리보기의 스크롤바 디자인을 변경했습니다
- `textarea` 포커스 시 아웃라인 색상을 변경했습니다
- 하단 파일 `input`의 이미지를 변경했습니다
- 스크롤바 코드
```
&::-webkit-scrollbar {
height: 6px;
}
&::-webkit-scrollbar-thumb {
background-color: var(--sub2-text-color);
border-radius: 6px;
}
```
- 아웃라인 코드
```
&:focus {
outline: 2px solid var(--main-disabled-color);
border-radius: 4px;
}
```
close : #183
=> 💄Style : PostUpload 페이지 스타일링 수정

src/pages/emailLogin/EmailLogin.jsx, src/pages/profileSetting/ProfileSetting.Style.jsx, src/pages/profileSetting/ProfileSetting.jsx
- profile setting page 기본이미지 설정 및 email Login page 스타일 수정
-
close : #
=> Modify : profile Setting page, emailLogin page input box 수정

src/common/product/Product.Style.jsx, src/common/product/Product.jsx, src/common/topBanner/TopBanner.jsx, src/pages/postDetail/PostDetail.jsx, src/pages/profile/Profile.jsx, src/pages/profile/postsDiv/PostsDiv.jsx, src/pages/profile/productDiv/ProductDiv.Style.jsx
=> Modify : useRef 오류 수정, 앨범형포스트 navigate 추가, 단순 오타 수정

src/pages/postDetail/PostDetail.Style.jsx, src/pages/postDetail/PostDetail.jsx
- 댓글 작성 시간 계산 오류로 0달 전으로 표시되는 현상을 수정했습니다
- 댓글의 프로필 클릭 시 해당 유저의 프로필 화면으로 이동하도록 변경했습니다
-
close : #
=> Modify : PostDetail 페이지 내 댓글에 navigate 함수 추가, 시간 계산 함수 수정

src/pages/profileSetting/ProfileSetting.jsx
- profile setting page 버튼 활성화
-
close : #
=> Modify : profile setting page 버튼 활성화

src/common/comment/Comment.Style.jsx, src/pages/chatRoom/ChatRoom.Style.jsx, src/pages/chatRoom/ChatRoom.jsx, src/pages/profileEdit/ProfileEdit.Style.jsx, src/pages/profileEdit/ProfileEdit.jsx
- 프로필 수정 페이지에서 유저의 프로필 이미지가 없을 경우, 기본 이미지를 보여줍니다.
- 채팅룸 페이지의 유저 프로필 사진을 변경했습니다.
- 채팅룸 페이지의 채팅 창에서 input 값이 입력되면 전송 버튼 색이 변경됩니다.
-
close : #
=> Add : ChatRoom 페이지 UI 수정

src/pages/home/Home.jsx
=> Modify : 홈피드페이지 moreBtn 구현

src/atoms/LoginData.js
=> Modify : LoginData 프로필 이미지 디폴트값 경로 수정

src/common/post/Post.Style.jsx, src/common/post/Post.jsx
- Post컴포넌트 캐러셀에 좌우이동 버튼을 추가했습니다
-
close : #197
=> 💄Style : Post컴포넌트 캐러셀에 arrow 버튼 추가

src/api/loadPostsAPI.js, src/api/loadProductsAPI.js, src/pages/postDetail/PostDetail.jsx, src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx, src/pages/profile/postsDiv/PostsDiv.Style.jsx, src/pages/profile/postsDiv/PostsDiv.jsx, src/pages/profile/productDiv/ProductDiv.Style.jsx, src/pages/profile/productDiv/ProductDiv.jsx, src/pages/profile/profileDiv/ProfileDiv.Style.jsx
=> Modify : postImg UI 수정 및 API 불러오기 데이터 개수제한삭제

src/api/getFollowersPostsAPI.js
- getFollowersPostsAPI 파일의 페이징 쿼리 코드를 수정했습니다
-
close : #
=> Modify : 피드데이터 API의 페이징 쿼리 수정

src/common/post/Post.jsx
=> Modify : 데이터 이미지 불러올때, 올바른 경로이미지만 불러오기 적용

src/api/joinAPI.js, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx, src/pages/profileSetting/ProfileSetting.jsx
- join page 버튼 활성화 수정
-
close : #206
=> Modify : join page 버튼 활성화 수정

src/api/getCommentListAPI.js, src/api/getPostDetailAPI.js, src/api/likeAPI.js, src/api/unlikeAPI.js, src/api/uploadImgAPI.js, src/api/uploadMultipleImgAPI.js, src/api/uploadPostAPI.js
- 아래 API 파일에 에러핸들링 코드를 추가했습니다
```
getCommentListAPI.js
getPostDetailAPI.js
likeAPI.js
unlikeAPI.js
uploadImgAPI.js
uploadMultipleImgAPI.js
uploadPostAPI.js
```
- 에러 내용이 사용자에게 보여야 할 경우 알림창으로 띄울 수 있도록 수정했습니다
-
close : #202
=> ✨Modify : API 에러핸들링 코드 추가

src/api/leaveCommentAPI.js, src/common/comment/Comment.Style.jsx, src/common/comment/Comment.jsx
-댓글 입력창에 공백문자만 입력될 경우 게시버튼이 활성화되지 않도록 수정했습니다
-공백만 입력됐을 경우에는 댓글 게시 API가 실행되지 않도록 수정했습니다
-
close : #208
=> 🐛Modify : 댓글 입력란에 공백만 입력할 경우 게시되지 않도록 수정

src/pages/postUpload/PostUpload.jsx
- PostUpload 페이지의 textarea에 value 속성을 추가해 setState 함수로만 제어 가능하도록 수정했습니다
- textarea 셀프클로징 처리를 복구했습니다
-
close : #
=> Modify : PostUpload 페이지 textarea에 value 속성 추가

src/pages/addProduct/AddProduct.jsx, src/pages/productEdit/ProductEdit.jsx, src/pages/profileEdit/ProfileEdit.jsx
=> :art:Modify : 프로필 수정, 상품 등록 및 수정 페이지 리팩토링

src/pages/join/Join.jsx
- oin page  비밀번호 활성화 기능 수정
-
close : #212
=> Modify : join page  비밀번호 활성화 기능 수정

src/pages/join/Join.jsx, src/pages/profileSetting/ProfileSetting.jsx
- navigate설정 수정
- 버튼 클릭 시 home화면으로 이동합니다.
close : #
=> Modify : navigate설정 수정

src/common/alert/Alert.jsx, src/common/post/Post.jsx, src/common/postModal/PostModal.Style.jsx, src/common/postModal/PostModal.jsx, src/pages/profile/Profile.jsx
=> Modify : 프로필페이지 모달 버튼버그 수정

src/api/editPostAPI.js, src/pages/postEdit/PostEdit.Style.jsx, src/pages/postEdit/PostEdit.jsx
- 게시글 수정 기능을 구현했습니다
- naviate 함수 오늘내로 수정 예정입니다
close : #
=> Feat : 게시글 수정 기능 구현

src/api/emailDuplicateAPI.js, src/api/joinAPI.js, src/pages/join/Join.jsx, src/pages/profileSetting/ProfileSetting.jsx
- Join API 수정 및 데이터 저장
-
close : #217
=> Modify : Join API 수정 및 데이터 저장

src/App.jsx, src/common/postModal/PostModal.jsx
=> Modify : 포스트 모달창 수정버튼 구현

src/common/postModal/PostModal.jsx, src/pages/chatList/ChatList.jsx
=> Modify : 채팅방 모달창로그아웃 구현, 설정 및 개인정보 버튼 navigate추가

src/pages/search/Search.Style.jsx
- 검색페이지의 스크롤바 영역이 보이지 않도록 수정했습니다
-
close : #
=> Modify : Search 페이지 스크롤 스타일링 수정

src/pages/profileSetting/ProfileSetting.jsx
- API token값 받아오기 수정했습니다.
-
close : #
=> Modify : API token값 받아오기 수정

src/pages/emailLogin/EmailLogin.jsx
- email, password input 입력시 활성화되도록 수정
-
close : #
=> Modify : email, password input 수정

src/App.jsx, src/pages/splash/Splash.jsx
- splash page snsLogin page setTimeOut으로 연결
-
close : #227
=> Modify : splash Page SnS Login page연결

src/pages/productEdit/ProductEdit.jsx
- 상품명, 상품 가격 공백 방지 및 버튼 비활성화
- 페이지 진입시 상품 가격 원 단위로 출력
- 상품 가격 0원 입력시 즉시 경고 메시지 출력 및 버튼 비활성화
-
close : #224
=> Modify : ProductEdit 페이지 피드백 반영하여 수정

src/pages/addProduct/AddProduct.jsx, src/pages/profileEdit/ProfileEdit.jsx
- 상품 등록 페이지 상품 가격 0원 입력시 버튼 비활성화
- 프로필 수정 페이지 유저 아이디 중복검사 onChange로 변경
-
close : #
=> Modify : ProfileEdit 유저 아이디 중복검사 onChange로 변경

src/App.jsx, src/pages/emailLogin/EmailLogin.jsx
- 이메일 로그인 안되는 이슈를 해결했습니다.
-
close : #
=> Modify : 로그인 안되는 이슈 해결

src/api/loadPostsAPI.js, src/pages/profileEdit/ProfileEdit.jsx, src/pages/profileSetting/ProfileSetting.jsx
=> Modify : ProfileSetting 유저 아이디 중복검사 onChange로 변경

src/common/alert/Alert.jsx, src/pages/addProduct/AddProduct.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/postEdit/PostEdit.jsx, src/pages/postUpload/PostUpload.jsx, src/pages/productEdit/ProductEdit.jsx, src/pages/profileEdit/ProfileEdit.jsx, src/pages/profileSetting/ProfileSetting.jsx
- EmailLogin 페이지 진입시 버튼이 활성화 되어있는 이슈를 해결했습니다.
- EmailLogin 페이지에서 잘못된 이메일 또는 비밀번호로 로그인했을 때 '이메일 또는 비밀번호가 일치하지 않습니다.' 에러 메시지를 출력하도록 변경했습니다.
- 모든 페이지에서 alert 코드를 임시로 주석처리했습니다.
-
close : #
=> Modify : EmailLogin 페이지 코드 수정

src/pages/snsLogin/SnsLogin.jsx, src/pages/splash/Splash.Style.jsx, src/pages/splash/Splash.jsx
- SNSLogin 페이지 진입 전에 SplashPage를 보여줍니다.
-
close : #
=> Feat : SNSLogin 이전에 SplashPage 보여주기

src/common/userBanner/UserBanner.jsx
=> Modify : 팔로우페이지 자신 계정 팔로우버튼 삭제

src/pages/productEdit/ProductEdit.jsx, src/pages/profileSetting/ProfileSetting.jsx
- 프로필 설정 페이지에서 유저 네임과 유저 아이디를 필수적으로 입력했을 때에만 버튼이 활성화되도록 변경했습니다.
-
close : #
=> Modify : ProfileSetting 유저 네임과 아이디만 버튼 활성화 필수 조건으로 변경

src/pages/profile/profileDiv/ProfileDiv.jsx
=> Modify : 팔로우 언팔로우 클릭시 팔로워 수 적용되도록 수정

src/api/editProfileAPI.js, src/pages/profileEdit/ProfileEdit.jsx
- 프로필 수정 시 변경된 유저 정보를 atom에 저장해 게시글 작성 페이지와 댓글 컴포넌트에서도 업데이트 되도록 수정했습니다
- uploadImgAPI는 submit 이벤트 발생 시 한번만 호출하도록 변경하였습니다
-
close : #
=> Modify : 프로필 수정 시 변경된 유저 정보 atom에 저장

src/styles/Globalstyled.jsx
=> 💄Add : 반응형 클래스 추가

src/common/tabMenu/TabMenu.Style.jsx
- 하단 탭메뉴의 반응형 디자인을 작업했습니다.
-
close : #
=> Style : Tabmenu 반응형 디자인

src/common/inputBox/InputBox.Style.jsx, src/pages/profileEdit/ProfileEdit.Style.jsx, src/pages/profileEdit/ProfileEdit.jsx
- 프로필 수정 페이지와 Inputbox 컴포넌트의 반응형 디자인을 작업했습니다.
-
close : #
=> Style : ProfileEdit 페이지 & InputBox 컴포넌트 반응형 디자인

src/pages/splash/Splash.Style.jsx, src/pages/splash/Splash.jsx
- splash page 반응형 작업
- splash page 이후 접근제한 수정 예정인 부분도 포함시켰습니다.
close : #243
=> Modify : splash page 반응형 작업

src/common/post/Post.Style.jsx
=> 📱Style : Post컴포넌트 반응형 디자인

src/pages/snsLogin/SnsLogin.Style.jsx, src/pages/snsLogin/SnsLogin.jsx, src/styles/Globalstyled.jsx
- sns login page 반응형 작업
- global style 탭 간격 수정했습니다!
close : #
=> Modify : sns login page 반응형 작업 및 global style 탭 수정

src/common/inputBox/InputBox.Style.jsx, src/pages/profileSetting/ProfileSetting.Style.jsx, src/pages/profileSetting/ProfileSetting.jsx
- 프로필 설정 페이지의 반응형 디자인을 작업했습니다.
- 하단 탭 메뉴 컴포넌트의 배경색을 #fff로 설정했습니다.
-
close : #
=> Style : ProfileSetting 페이지 반응형 디자인

src/pages/snsLogin/SnsLogin.jsx
- snsLogin page min-width 추가
-
close : #
=> Modify : snsLogin page 반응형 min-width 추가

src/common/comment/Comment.Style.jsx, src/common/comment/Comment.jsx
- Comment 컴포넌트의 반응형 디자인을 작업했습니다.
-
close : #
=> Style : Comment 컴포넌트 반응형 디자인

src/common/alert/Alert.Style.jsx, src/common/alert/Alert.jsx, src/common/postModal/PostModal.Style.jsx, src/common/postModal/PostModal.jsx, src/common/topBanner/TopBanner.Style.jsx, src/common/topBanner/TopBanner.jsx, src/pages/profile/Profile.Style.jsx, src/pages/profile/Profile.jsx, src/pages/profile/postsDiv/PostsDiv.Style.jsx, src/pages/profile/profileDiv/ProfileDiv.Style.jsx
=> Modify : 반응형 적용 및 모달 alert창 UI 추가수정

src/common/topBanner/TopBanner.Style.jsx
=> Modify : 탑배너 UI 수정

src/common/topBanner/TopBanner.Style.jsx
=> Modify : z-index

src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx
- email login page 반응형 작업
-
close : #
=> Modify : emailLogin page 반응형 작업

src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.Style.jsx, src/pages/join/Join.jsx
- join page 반응형 작업
-
close : #
=> Modify : join page 반응형 작업

src/pages/join/Join.jsx
- join page 버튼 반응형 작업 수정
-
close : #
=> Modify : join page 버튼 반응형 수정

src/pages/emailLogin/EmailLogin.jsx
- email login page 반응형 버튼 수정
-
close : #
=> Modify : email login page 반응형 버튼 수정

src/pages/addProduct/AddProduct.Style.jsx, src/pages/addProduct/AddProduct.jsx, src/pages/chatList/ChatList.Style.jsx, src/pages/chatList/ChatList.jsx, src/pages/productEdit/ProductEdit.Style.jsx, src/pages/productEdit/ProductEdit.jsx, src/pages/profileEdit/ProfileEdit.Style.jsx
- 상품 등록, 수정, 채팅 리스트 페이지의 반응형 디자인을 작업했습니다.
-
close : #
=> Style : 상품 등록, 상품 수정, ChatList 페이지 반응형 디자인

src/common/userBanner/UserBanner.Style.jsx, src/common/userBanner/UserBanner.jsx
=> Modify : UserBanner 반응형 수정

src/pages/followingList/FollowingList.Style.jsx, src/pages/followingList/FollowingList.jsx
- following list page 반응형 작업
-
close : #
=> Modify : following list page 반응형 작업

src/common/alert/Alert.Style.jsx, src/common/postModal/PostModal.Style.jsx
=> Modify : 모달 및 알림창 z-index 수정

src/pages/emailLogin/EmailLogin.Style.jsx, src/pages/join/Join.Style.jsx, src/pages/join/Join.jsx
=> Modify : 로그인 & 회원가입 페이지 버튼 간격 수정

src/pages/chatRoom/ChatRoom.Style.jsx, src/pages/postUpload/PostUpload.Style.jsx
- 채팅룸과 게시글 업로드 페이지의 스크롤을 삭제했습니다
-
close : #
=> 📱Modify : ChatRoom, PostUpload페이지 스크롤 수정

src/pages/chatRoom/ChatRoom.Style.jsx
=> 🩹Modify : 채팅방 애니메이션 시작시 스크롤이 나타나는 현상 수정

src/App.jsx
- PrivateRoutesRev구조 수정
-
close : #
=> Modify : 접근제한 PrivateRoutesRev route구조 수정

src/pages/profile/Profile.jsx, src/pages/profile/postsDiv/PostsDiv.jsx, src/pages/profile/productDiv/ProductDiv.jsx, src/pages/profile/profileDiv/ProfileDiv.jsx
=> Modify : 프로필페이지 리다이렉션 버그 수정

src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx
- signup 파일명 join으로 수정
-
close : #
=> 💬Modify : signup join으로 수정

src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx, src/pages/profileSetting/ProfileSetting.jsx
- 프로필 셋팅 후 isLogin 상태값을 true로 바꾸지 않아 sns로그인 페이지로 리다이렉트되는 현상을 수정했습니다.
-
close : #
=> 🐛Modify : 프로필 셋팅 폼 제출 후 sns로그인으로 돌아가는 문제 수정

src/App.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx, src/pages/splash/Splash.jsx, src/routes/privateRoutes.jsx, src/routes/privateRoutesRev.jsx
- 코드의 논리성에 맞게 PrivateRoutes와 PrivateRoutesRev를 서로 교체했습니다.
-
close : #
=> Modify : PrivateRoutes 수정

README.md, src/common/alert/Alert.jsx, src/common/inputBox/InputBox.jsx, src/pages/addProduct/AddProduct.jsx, src/pages/chatRoom/ChatRoom.jsx, src/pages/emailLogin/EmailLogin.jsx, src/pages/join/Join.jsx, src/pages/postEdit/PostEdit.jsx, src/pages/postUpload/PostUpload.jsx, src/pages/productEdit/ProductEdit.jsx, src/pages/profileEdit/ProfileEdit.jsx, src/pages/profileSetting/ProfileSetting.jsx, src/pages/snsLogin/SnsLogin.jsx
=> Modify : 페이지 필요 없는 주석 삭제 및 함수명 수정
